services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "5672:5672" # RabbitMQ AMQP
    environment:
      RABBITMQ_HOST: '%'
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: root
      RABBITMQ_DEFAULT_VHOST: myvhost 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    driver: local